apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test
  name: test
spec:
  ports:
  - name: 5432-80
    nodePort: 32000
    port: 5432
    protocol: TCP
    targetPort: 9080
  selector:
    app: hello 
  type: NodePort
status:
  loadBalancer: {}
