apiVersion: v1 

kind: Pod

metadata:
  name: myapp-pod
  labels:
    app: myapp
    

spec:
  containers: 
    - name: nginx-container
      image: nginx
  resources:  # resources container requests
    requests:
      cpu: 2
      memory: "4Gi"
