apiVersion: v1 

kind: Pod

metadata:
  name: myapp-pod
  labels:
    app: myapp
    

spec:
  containers: 
    - name: simple-webapp
      image: simple-webapp
      ports:
        - containerPort: 8080
    - name: log-agent   # multi-container pod
      image: log-agent  
  resources:  # resources container requests
    requests:
      memory: "1Gi"
      cpu: 2
    limits:   # limits resources container may use
      memory: "2Gi"
      cpu: 2
